on:
  push:
  workflow_dispatch:

jobs:
  azuread:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Microsoft Azure
      shell: pwsh
      run: |
        $tenant = "${{ secrets.AZURE_ACTIVE_DIRECTORY_TENANT }}"
        $username = "${{ secrets.AZURE_APP_REGISTRATION }}"
        $password = "${{ secrets.AZURE_CLIENT_SECRET }}"
        az login --service-principal --tenant $tenant  --username $username --password $password
